In [2]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from keras.optimizers import SGD
import numpy as np
import tensorflow as tf
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.datasets import boston_housing, mnist, cifar10, imdb

In [7]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()
(x_train2,y_train2),(x_test2,y_test2) = boston_housing.load_data()
(x_train3,y_train3),(x_test3,y_test3) = cifar10.load_data()
(x_train4,y_train4),(x_test4,y_test4) = imdb.load_data(num_words=20000)
num_classes = 10

In [8]:
from keras.preprocessing import sequence
x_train4 = sequence.pad_sequences(x_train4,maxlen=80)
x_test4 = sequence.pad_sequences(x_test4,maxlen=80)

In [9]:
from keras.utils import to_categorical
Y_train = to_categorical(y_train, num_classes)
Y_test = to_categorical(y_test, num_classes)
Y_train3 = to_categorical(y_train3, num_classes)
Y_test3 = to_categorical(y_test3, num_classes)

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(x_train2)
standardized_X = scaler.transform(x_train2)
standardized_X_test = scaler.transform(x_test2)

In [15]:
from keras.models import Sequential
model = Sequential()
model2 = Sequential()
model3 = Sequential()

In [23]:
from keras.layers import Embedding,LSTM
model3.add(Embedding(20000,128))
model3.add(LSTM(128,dropout=0.2,recurrent_dropout=0.2))
model3.add(Dense(1,activation='sigmoid'))

In [24]:
model3.get_weights()

[array([[ 0.03567079,  0.02103115, -0.03921535, ...,  0.04068412,
         -0.00427121,  0.02989329],
        [ 0.02425087,  0.04393959, -0.02337098, ..., -0.0396953 ,
          0.03014319,  0.00329865],
        [ 0.02133382,  0.00258126,  0.0275251 , ..., -0.03300913,
         -0.04363573,  0.00673517],
        ..., 
        [ 0.03098882, -0.00271281,  0.03247558, ..., -0.04598729,
         -0.03340856,  0.04932082],
        [-0.00133841,  0.0034353 ,  0.00330983, ...,  0.0365073 ,
         -0.02707888,  0.03125966],
        [-0.04768633, -0.00668116, -0.04024322, ..., -0.02213682,
         -0.03810485, -0.00014136]], dtype=float32),
 array([[-0.01483003,  0.01853339,  0.01698656, ..., -0.07596578,
          0.05723952,  0.04353812],
        [ 0.07548054,  0.08890048,  0.07158279, ...,  0.02137499,
          0.02323437, -0.0285612 ],
        [-0.02916092,  0.08972736, -0.0870176 , ...,  0.062527  ,
          0.06265938, -0.00703003],
        ..., 
        [ 0.01300781, -0.06374539, -0

In [27]:
model3.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [31]:
model3.fit(x_train4, y_train4, batch_size=32, epochs=1, verbose=1, validation_data=(x_test4, y_test4))

Train on 25000 samples, validate on 25000 samples
Epoch 1/1
25000/25000 [==============================] - 203s - loss: 0.0767 - acc: 0.9737 - val_loss: 0.7006 - val_acc: 0.8189


In [35]:
score = model3.evaluate(x_test4, y_test4, batch_size=32)

24992/25000 [============================>.] - ETA: 0s

In [37]:
model3.predict(x_test4, batch_size=32)

array([[ 0.99892163],
       [ 0.03004251],
       [ 0.83453339],
       ..., 
       [ 0.99976903],
       [ 0.0296329 ],
       [ 0.99835759]], dtype=float32)

In [38]:
model3.predict_classes(x_test4,batch_size=32)

24992/25000 [============================>.] - ETA: 0s

array([[1],
       [0],
       [1],
       ..., 
       [1],
       [0],
       [1]])

In [41]:
from keras.models import load_model
model3.save('model_file.h5')
my_model = load_model('my_model.h5')

OSError: Unable to open file (unable to open file: name = 'my_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)